version: 2.1

orbs:
  kubernetes: oak/kubernetes@dev:76f6857
  utils: oak/utils@0.0.1
  aws-cli: circleci/aws-cli@3.1.1

aliases:
  - &only-master
    branches:
      only:
        - master

  - &only-prs
    branches:
      ignore:
        - master

  - &base-image
    resource_class: small
    docker:
      - image: cimg/base:2022.03

  - &devops-image
    resource_class: small
    docker:
      - image: 049961945951.dkr.ecr.us-east-1.amazonaws.com/devops-neo:3

  - &run-on-release
    filters:
      tags:
        only:
          - /\d+\.\d+\.\d+/
      branches:
        ignore: /.*/

  - &ssh-fingerprint
    fingerprints:
      - 0f:f3:91:06:fd:7c:18:ed:bc:3d:8c:74:f6:59:a2:12

jobs:
  create-git-tag:
    <<: [*devops-image]
    steps:
      - checkout
      - add_ssh_keys:
          <<: *ssh-fingerprint
      - utils/create-git-tag

  container-build-push:
    <<: [*base-image]
    parameters:
      repo:
        type: string
        description: 'Name of the container image repo to build without the registry prefix'
      tag:
        type: string
        description: 'Tag that image should have'
        default: 'sha-${CIRCLE_BRANCH}-${CIRCLE_SHA1:0:7}-$(date +%F)-${CIRCLE_BUILD_NUM}'
    steps:
      - checkout
      - kubernetes/container-build-push:
          path: ./
          dockerfile: Dockerfile
          repo: << parameters.repo >>
          tag: << parameters.tag >>


workflows:
  git-tag-creation-workflow:
    jobs:
      - create-git-tag:
          context: marmot-deploy-dev
          filters:
            <<: *only-master

  container-workflow:
    jobs:
      - kubernetes/kube-linter:
          name: kube-linter
          context: marmot-deploy-dev
      - container-build-push:
          name: Build and Push
          repo: aws-es-proxy
          context: marmot-deploy-dev
          requires:
            - kube-linter
