version: 2.1

.deploy: &deploy
    machine: true
    working_directory: ~/workspace
    steps:
    - checkout:
        path: ~/workspace
    - run:
        name: ecr_auth_push
        command: |
          bash ~/workspace/.circleci/get_auth_ecr.sh

.only-prod-tag: &only-prod-tag
  filters:
    branches:
      only:
        - master
    tags:
      only: '/^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/'

.container_executor: &container_executor
   docker:
     - image: circleci/python:3.6.1

.directory: &directory
   working_directory: ~/workspace

jobs:
  checkout-code:
    <<: *container_executor
    <<: *directory
    steps:
      - checkout

  deploy:
    <<: *deploy

workflows:
  version: 2
  pipeline:
    jobs:
    - checkout-code
    - deploy:
        context: CIRCLE_CI_AWS_IAM_EMEA_EKS_STAGE
        <<: *only-prod-tag
        requires:
          - checkout-code
