apiVersion: v1
kind: Pod
metadata:
  annotations:
    iam.amazonaws.com/role: "KubernetesJenkinsAgent"
spec:
  containers:
    - name: go
      image: "golang:1.14-alpine"
      command: ["cat"]
      tty: true
    - name: docker
      image: '772592230491.dkr.ecr.eu-west-1.amazonaws.com/docker:latest'
      command: ["cat"]
      tty: true
      volumeMounts:
        - name: docker-socket
          mountPath: "/var/run/docker.sock"
    - name: notifications
      image: '772592230491.dkr.ecr.eu-west-1.amazonaws.com/jenkins-notifications:v0.1.9.1'
      command: ["cat"]
      tty: true
      env:
        - name: SLACK_WEBHOOK_ADDRESS
          valueFrom:
            secretKeyRef:
              name: jenkins-notifications-secret
              key: slack-webhook-url
  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
    - name: maven-cache
      hostPath:
        path: /root/.m2
